### ISSUE TITLE
confusion with ibagomel visual flow project

### ISSUE THREAD

**Issue by sandrinesuire** [ibagroup-eu/Visual-Flow#5]
What is the difference between your project and ibagomel visual flow project 

I found no information on internet and in your youtube video description https://www.youtube.com/watch?v=lITIK-p77EE, you link to their project https://github.com/ibagomel/Visual-Flow-deploy/blob/amazon/INSTALL.md.

So it is confused for me.

**Comment by AGSadovsky** [comment]
Hey Sandrine @sandrinesuire ,
we moved our project from ibagomel to ibagroup-eu organization for some major reasons related to headquarters location change. You can find the latest code version in the current repository. Previous one is outdated and not supported anymore. The link reference will be fixed in the next release. Here's the correct one: https://github.com/ibagroup-eu/Visual-Flow-deploy/blob/amazon/INSTALL.md
Thanks for your notice and let us know if you have other concerns.
